# Generated by Django 5.0.4 on 2024-12-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_remove_progresslog_weight_progresslog_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progresslog',
            name='log',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
