# Generated by Django 5.0.4 on 2024-11-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_appuser_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.AddField(
            model_name='appuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
