# Generated by Django 5.0.4 on 2024-11-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_age_appuser_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='short_description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
