# Generated by Django 5.0.4 on 2024-12-11 18:34

from django.db import migrations


def create_admin_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")

    # Create or get groups
    superusers_group, _ = Group.objects.get_or_create(name="Superusers")
    staff_group, _ = Group.objects.get_or_create(name="Staff")

    # Assign permissions to Staff group
    # Define limited permissions (customize as needed)
    staff_permissions = Permission.objects.filter(
        codename__in=[
            "change_workoutcategory", "view_workoutcategory",
            "change_workout", "view_workout",
            "change_profile", "view_profile",
            "change_favouriteworkouts", "view_favouriteworkouts",
            "change_meal", "view_meal",
            "change_progressexercise", "view_progressexercise",
            "change_progresslog", "view_progresslog"
        ]
    )
    staff_group.permissions.set(staff_permissions)


def remove_admin_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name__in=["Superusers", "Staff"]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0009_alter_appuser_first_name_alter_appuser_last_name_and_more'),
    ]

    operations = [
    ]
