# Generated by Django 5.0.4 on 2024-12-11 19:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_create_admin_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='first_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2, ('The first name must contain at least 2 symbols!',))]),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='last_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2, ('The last name must contain at least 2 symbols!',))]),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(2, ('The username must contain at least 2 symbols!',))]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1, ('The height must be a positive number!',))]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1, ('The weight must be a positive number!',))]),
        ),
    ]
