# Generated by Django 5.0.4 on 2024-12-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='ingredients',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.AddField(
            model_name='meal',
            name='ingredients',
            field=models.TextField(default='None'),
        ),
    ]
