# Generated by Django 5.0.4 on 2024-12-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_remove_meal_ingredients_delete_ingredient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='ingredients',
            field=models.TextField(blank=True, null=True),
        ),
    ]
